# Generated by Django 4.2.5 on 2023-10-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HRapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_applicant_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'job_seeker_details',
            },
        ),
        migrations.CreateModel(
            name='application_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField()),
                ('cover_letter', models.CharField(max_length=1000)),
                ('resume', models.FileField(upload_to='')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseekerapp.class_applicant_signup')),
                ('job_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRapp.job_posting')),
            ],
            options={
                'db_table': 'job_application_form',
            },
        ),
    ]
