# Generated by Django 4.2.5 on 2023-11-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0002_application_form_date_alter_application_form_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_applicant_signup',
            name='status',
            field=models.CharField(default='Active', max_length=50, null=True),
        ),
    ]
