# Generated by Django 4.2.5 on 2023-10-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=30)),
                ('company_contact', models.CharField(max_length=20)),
                ('company_password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'hr_signup',
            },
        ),
        migrations.CreateModel(
            name='job_posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=1000)),
                ('job_location', models.CharField(max_length=50)),
                ('job_salary', models.CharField(max_length=50)),
                ('job_experience', models.CharField(max_length=50)),
                ('job_posting_date', models.DateField()),
                ('job_closing', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRapp.company_signup')),
            ],
            options={
                'db_table': 'hr_job_posting',
            },
        ),
    ]
