# Generated by Django 4.2.5 on 2023-11-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=30)),
                ('admin_contact', models.CharField(max_length=20)),
                ('admin_password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'admin_signup',
            },
        ),
    ]
